spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpaspringboot1;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # application 실행시점에 내가 가진 데이터 다 지우고 다시 create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
  org.hibernate.orm.jdbc.bind: trace